In [ ]:
import pandas as pd

In [ ]:
df=pd.read_csv("/content/noon_perfumes_dataset.csv")

In [ ]:
df.head()#عرض اول 5 صفوف

,Unnamed: 0,brand,name,old_price,new_price,ml,concentration,department,scents,base_note,middle_note,item_rating,seller,seller_rating,num_seller_ratings
0,0,PACO RABANNE,1 Million Lucky,395.0,244.55,100,EDT,Men,Woody,"Oakmoss, Patchouli and Vetiver","Hazelnut, Jasmine, Cashmir Wood, Cedar and Honey",5.0,noon,4.2,98.1K
1,1,Roberto Cavalli,Paradiso Assoluto,415.0,107.95,50,EDP,Women,Floral,"Vanilla, Sandalwood And Patchouli",Wild Jasmine and Red Lily,4.8,noon,4.2,98.1K
2,2,S.T.Dupont,Royal Amber,265.0,186.90,100,EDP,Unisex,Arabian,"Lemon, Mint and Wood Moss",Sandalwood and Cedar,5.0,noon,4.2,98.1K
3,3,GUESS,Seductive Blue,290.0,103.20,100,EDT,Men,Spicy,"Cashmere Wood, Moss And Rippled Sand Accord",Blue Coral Aquaspace Accord And Geranium,3.0,noon,4.2,98.1K
4,4,Roberto Cavalli,Uomo,260.0,94.95,50,EDP,Women,Arabian,"Vanille, Benzoin, Tonka Bean",African Orange Flower,4.8,noon,4.2,98.1K

In [ ]:
df.tail()#عرض اخر 5 صفوف

,Unnamed: 0,brand,name,old_price,new_price,ml,concentration,department,scents,base_note,middle_note,item_rating,seller,seller_rating,num_seller_ratings
998,998,GUESS,Dare,170.0,75.00,100,EDT,Women,Citrus,"Coconut Accords, Wood, Musk","Wild Rose, Elegant Jasmine",4.9,noon,4.2,98.1K
999,999,BURBERRY,For Women EDP Natural Sp,378.0,153.75,100,EDT,Women,Fruity,Musk And Vanilla,"Woody-Floral, Sandalwood And Cedar",4.8,noon,4.2,98.1K
1000,1000,JOVAN,Musk Cologne Sp,55.0,19.00,59,EDT,Women,Woody,"Musk, Amber, Wood",Ylang-ylang,4.7,Cute,3.7,1.9K
1001,1001,SWISS ARABIAN,Layali CPO At,126.0,77.00,15,EDT,Unisex,Arabian,Agarwood and Amber,"Ylang-Ylang, Rose and Jasmine",4.0,Swiss Arabian PerfumesPRICE UPDATE WITH 15% VA...,3.9,5
1002,1002,LACOSTE,L.12.12 Blanc-Pure,347.0,94.20,100,EDT,Men,Woody,"Virginia Cedar, Leather, Suede, Vetiver","Ylang-Ylang, Tuberose",4.6,noon,4.2,98.1K

In [ ]:
df.sample() #عررض  صفوف عشوائئ

,Unnamed: 0,brand,name,old_price,new_price,ml,concentration,department,scents,base_note,middle_note,item_rating,seller,seller_rating,num_seller_ratings
447,447,LALIQUE,Le'Parfum,143.0,143.0,100,EDP,Women,Oriental,"Sandalwood, Tonka Bean, Patchouli and Vanilla",Jasmine and Heliotrope,4.4,Beautiful Live,412.0,7

In [ ]:
df.info()  #عرض معلومات عن الداتا

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1003 entries, 0 to 1002
Data columns (total 15 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1003 non-null   int64
 1   brand               1003 non-null   object
 2   name                1003 non-null   object
 3   old_price           1003 non-null   float64
 4   new_price           1003 non-null   float64
 5   ml                  1003 non-null   int64
 6   concentration       1003 non-null   object
 7   department          1003 non-null   object
 8   scents              1003 non-null   object
 9   base_note           1003 non-null   object
 10  middle_note         1003 non-null   object
 11  item_rating         1003 non-null   float64
 12  seller              1003 non-null   object
 13  seller_rating       1003 non-null   float64
 14  num_seller_ratings  1003 non-null   object
dtypes: float64(4), int64(2), object(9)
memory usage: 117.7+ KB

In [ ]:
df.shape #عرض شكل الداتا الللي هما الصفوف والاعمده

(1003, 15)

In [ ]:
df.columns #عرض اسماء الاعمده

Index(['Unnamed: 0', 'brand', 'name', 'old_price', 'new_price', 'ml',
       'concentration', 'department', 'scents', 'base_note', 'middle_note',
       'item_rating', 'seller', 'seller_rating', 'num_seller_ratings'],
      dtype='object')

In [ ]:
df.describe() # وصف الداتا

,Unnamed: 0,old_price,new_price,ml,item_rating,seller_rating
count,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000,1003.000000
mean,501.000000,321.176022,149.574307,92.862413,4.530907,14.143170
std,289.685462,234.195846,108.686013,27.496053,0.555504,64.706572
min,0.000000,5.350000,5.350000,1.000000,1.000000,3.500000
25%,250.500000,140.500000,80.325000,80.000000,4.400000,3.800000
50%,501.000000,310.000000,135.000000,100.000000,4.600000,3.900000
75%,751.500000,455.000000,198.525000,100.000000,5.000000,4.200000
max,1002.000000,2350.000000,904.850000,200.000000,5.000000,454.000000

In [ ]:
df.duplicated().sum() #  بشوف في تكرار ولا لا

np.int64(0)

In [ ]:
df.nunique()# القيم الفريده اللي موجوده

Unnamed: 0            1003
brand                  160
name                   594
old_price              438
new_price              644
ml                      28
concentration            5
department               4
scents                  22
base_note              739
middle_note            726
item_rating             23
seller                 117
seller_rating           15
num_seller_ratings      60
dtype: int64

In [ ]:
df.isnull().sum() #بشوف القيم الفارغه الموجوده

Unnamed: 0            0
brand                 0
name                  0
old_price             0
new_price             0
ml                    0
concentration         0
department            0
scents                0
base_note             0
middle_note           0
item_rating           0
seller                0
seller_rating         0
num_seller_ratings    0
dtype: int64

In [ ]:
df.drop(columns='Unnamed: 0', inplace=True)

In [ ]:
df['num_seller_ratings'] = (
    df['num_seller_ratings']
      .str.replace('K', '', regex=False)
      .astype(float)
      * 1000
      ).astype(int)

In [ ]:
df['discount_amount'] = df['old_price'] - df['new_price']

In [ ]:
df['discount_percentage'] = (
    (df['old_price'] - df['new_price']) / df['old_price'] * 100
).round(2)

In [ ]:
df.isnull().sum() #بشوف القيم الفارغه الموجوده

brand                  0
name                   0
old_price              0
new_price              0
ml                     0
concentration          0
department             0
scents                 0
base_note              0
middle_note            0
item_rating            0
seller                 0
seller_rating          0
num_seller_ratings     0
discount_amount        0
discount_percentage    0
dtype: int64

In [ ]:
df.to_csv("noon_perfumes_clean.csv", index=False)